import { COPY_TERMS } from './terms';

/** 頁面標題與區塊標題 */
export const COPY_PAGES = {
  home: '首頁',
  ledger: COPY_TERMS.ledger,
  changes: '變更',
  changesSubtitle: '誰改了什麼、什麼時候',
  recentRecords: '最近記帳',
  whatHappened: '發生什麼事',
  howToSplit: '怎麼分',
  whoPaid: '誰先付',
  splitResult: '分攤結果',
  splitChart: '分攤圖',
  eachAmount: '每人多少',
  recordType: '這是什麼類型',
  oweNow: '現在欠多少',
  whoOwesMost: '誰欠最多',
  whoOwesMostHint: '欠的扣掉先付收回，負最多前三名',
  whoShouldRepayYou: '誰該還你',
  whoShouldRepayYouHint: '可複製提醒訊息，方便跟家人說',
  selectToConsolidate: '勾選要整合的記錄',
  selectedRecords: (n: number) => `已勾選記錄（${n} 筆）`,
  consolidateDetail: '整合明細',
  settlementWith: (name: string) => `${name} · 還沒還清的明細`,
  settlementDetailHint:
    '欠的扣掉先付與還款，以下分別列出跟各家人的往來',
  memberPendingDetail: (name: string) => `${name} 的待結清明細`,
  youOweThem: '你欠他',
  theyOweYou: '欠你',
  payment: '付款',
  split: COPY_TERMS.split,
  repayment: COPY_TERMS.repayment,
  note: '備註',
  date: '日期',
  eachPersonAmount: '各人金額',
  viewFullDetail: '查看完整詳情 →',
  createdBy: (name: string) => `由 ${name} 記的`,
  interestNoSplit: '這筆沒有需要試算利息的分攤',
  noPendingSettlement: '目前沒有待結清的款項',
  ledgerHealthy: '帳本狀態良好',
  netOwe: '目前淨欠',
  netReceive: '目前淨收',
  ledgerClear: '帳本已清',
  /** 完全沒有往來欠款時的 hero 文案 */
  ledgerNoDebt: '恭喜你沒有債務纏身',
  totalYouOwe: '你欠',
  totalOwedYou: '欠你',
  settlementsWith: '跟誰有帳',
  settlementsEmpty: '目前沒有跟任何人的往來帳款',
  priorityRepay: (name: string, amount: string) => `優先還給 ${name} ${amount}`,
  pickSettlementOwe: '你欠誰？',
  pickSettlementOwed: '誰欠你？',
  currentLedger: '目前帳務',
  rankEmpty: '目前沒有人淨欠款，大家很乖',
  remindEmpty: '目前沒有人欠你，不用催',
} as const;
