import {
  filterManualLineItems,
  isAutoGeneratedLineItem,
  participantLineItemsWithChange,
  participantServiceFeeShare,
  participantSharedConsumptionShare,
  SERVICE_FEE_NOTE,
  SHARED_CONSUMPTION_NOTE,
} from './advance-display';
import { Transaction } from '../models';

describe('advance-display line items', () => {
  it('identifies auto-generated change line items', () => {
    expect(isAutoGeneratedLineItem({ note: '找錢（已退回）', amount: 257 })).toBe(
      true
    );
    expect(isAutoGeneratedLineItem({ note: '待他人結算', amount: 743 })).toBe(
      true
    );
    expect(
      isAutoGeneratedLineItem({ note: SHARED_CONSUMPTION_NOTE, amount: 325 })
    ).toBe(true);
    expect(isAutoGeneratedLineItem({ note: SERVICE_FEE_NOTE, amount: 20 })).toBe(
      true
    );
    expect(isAutoGeneratedLineItem({ note: '慕斯瓶', amount: 79 })).toBe(false);
  });

  it('filters manual items for edit hydration', () => {
    expect(
      filterManualLineItems([
        { note: '找錢（已退回）', amount: 257 },
        { note: '慕斯瓶', amount: 79 },
        { note: SHARED_CONSUMPTION_NOTE, amount: 325 },
        { note: SERVICE_FEE_NOTE, amount: 20 },
        { note: '待他人結算', amount: 743 },
      ])
    ).toEqual([{ note: '慕斯瓶', amount: 79 }]);
  });

  it('appends shared consumption when exclusive items leave a remainder', () => {
    const tx: Transaction = {
      id: 'tx1',
      accountId: 'default',
      type: 'advance',
      title: '全家',
      totalAmount: 821,
      payerId: 'lin',
      payers: [{ memberId: 'lin', amount: 821 }],
      splitMode: 'itemized',
      status: 'active',
      createdBy: 'lin',
      createdAt: '2026-07-15T00:00:00.000Z',
      updatedAt: '2026-07-15T00:00:00.000Z',
      participants: [
        {
          memberId: 'lin',
          amount: 439,
          signedAmount: 439,
          lineItems: [
            { note: '麥片牛奶', amount: 35 },
            { note: '燕麥餅乾', amount: 79 },
          ],
        },
        {
          memberId: 'zheng',
          amount: 382,
          signedAmount: 382,
          lineItems: [
            { note: '蜜桃蘇打', amount: 19 },
            { note: '蜜桃蘇打', amount: 19 },
            { note: '葡萄蘇打', amount: 19 },
          ],
        },
      ],
    };

    expect(
      participantSharedConsumptionShare(tx, tx.participants[0])
    ).toBe(325);
    expect(
      participantSharedConsumptionShare(tx, tx.participants[1])
    ).toBe(325);

    expect(participantLineItemsWithChange(tx, tx.participants[1])).toEqual([
      { note: '蜜桃蘇打', amount: 19 },
      { note: '蜜桃蘇打', amount: 19 },
      { note: '葡萄蘇打', amount: 19 },
      { note: SHARED_CONSUMPTION_NOTE, amount: 325 },
    ]);
  });

  it('appends service fee share on detail breakdown', () => {
    const tx: Transaction = {
      id: 'tx-fee',
      accountId: 'default',
      type: 'advance',
      title: '吃飯',
      totalAmount: 330,
      serviceFee: 30,
      serviceFeeSplitMode: 'proportional',
      payerId: 'a',
      payers: [{ memberId: 'a', amount: 330 }],
      splitMode: 'itemized',
      status: 'active',
      createdBy: 'a',
      createdAt: '2026-07-15T00:00:00.000Z',
      updatedAt: '2026-07-15T00:00:00.000Z',
      participants: [
        { memberId: 'a', amount: 220, signedAmount: 220 },
        { memberId: 'b', amount: 110, signedAmount: 110 },
      ],
    };

    expect(participantServiceFeeShare(tx, tx.participants[0])).toBe(20);
    expect(participantServiceFeeShare(tx, tx.participants[1])).toBe(10);
    expect(participantLineItemsWithChange(tx, tx.participants[0])).toEqual([
      { note: SERVICE_FEE_NOTE, amount: 20 },
    ]);
  });
});