import { LineItem, Transaction } from '../models';
import {
  advanceChangeAmount,
  advanceChangeShareByMember,
  advanceMemberBalances,
  advanceNetPaidByMember,
  advanceSharesByMember,
  getAdvancePayers,
} from '../transactions/advance-allocation';
import {
  normalizeServiceFeeSplitMode,
  serviceFeeSharesByMember,
} from './service-fee-split';

export const SHARED_CONSUMPTION_NOTE = '共同消費' as const;
export const SERVICE_FEE_NOTE = '服務費' as const;

export interface PayerChangeBreakdown {
  changeShare: number;
  settlementNet: number;
  displayNet: number;
  lineItems: LineItem[];
}

/** 代墊者找錢明細（顯示用，不影響結算） */
export function payerChangeBreakdown(
  tx: Transaction,
  memberId: string
): PayerChangeBreakdown | null {
  const payer = getAdvancePayers(tx).find((p) => p.memberId === memberId);
  if (!payer) return null;

  const changeShare = advanceChangeShareByMember(tx).get(memberId) ?? 0;
  if (changeShare <= 0) return null;

  const share = advanceSharesByMember(tx).get(memberId) ?? 0;
  const settlementNet = advanceMemberBalances(tx).get(memberId) ?? 0;
  const lineItems: LineItem[] = [
    { note: '找錢（已退回）', amount: changeShare },
  ];

  let displayNet = settlementNet;
  if (share === 0) {
    displayNet = payer.amount;
    if (settlementNet > 0) {
      lineItems.push({ note: '待他人結算', amount: settlementNet });
    }
  }

  return { changeShare, settlementNet, displayNet, lineItems };
}

export function isAutoGeneratedLineItem(item: LineItem): boolean {
  return (
    item.note.includes('找錢') ||
    item.note === '待他人結算' ||
    item.note === SHARED_CONSUMPTION_NOTE ||
    item.note === SERVICE_FEE_NOTE
  );
}

/** 過濾系統自動附加的找錢／共同消費明細（編輯載入用） */
export function filterManualLineItems(items: LineItem[] | undefined): LineItem[] {
  return (items ?? []).filter((item) => !isAutoGeneratedLineItem(item));
}

/** 這筆是否有專屬細項（有的話才可能有平分的共同消費） */
export function transactionHasManualLineItems(tx: Transaction): boolean {
  return tx.participants.some(
    (p) => filterManualLineItems(p.lineItems).length > 0
  );
}

/** 含服務費的應付額 → 還原基礎分攤（與編輯載入同一套種子：tx.id） */
export function participantBaseAmountBeforeFee(
  tx: Transaction,
  participant: { memberId: string; amount: number }
): number {
  const fee = tx.serviceFee ?? 0;
  if (fee <= 0) return Math.max(0, participant.amount);

  const payingIds = tx.participants
    .filter((p) => p.amount > 0)
    .map((p) => p.memberId);
  const mode = normalizeServiceFeeSplitMode(tx.serviceFeeSplitMode);
  const inclusiveAmounts = Object.fromEntries(
    tx.participants.map((p) => [p.memberId, p.amount])
  );
  const shares = serviceFeeSharesByMember(fee, payingIds, tx.payerId, tx.id, {
    mode,
    // 比例分：以含服務費金額當權重反推（與基礎消費同比例）
    baseAmountsByMember: mode === 'proportional' ? inclusiveAmounts : undefined,
  });
  return Math.max(0, participant.amount - (shares.get(participant.memberId) ?? 0));
}

/**
 * 該員分到的共同消費（平分剩餘）：基礎應付 − 專屬細項。
 * 建立頁有寫這一行，詳情列表也要對齊。
 */
export function participantSharedConsumptionShare(
  tx: Transaction,
  participant: { memberId: string; amount: number; lineItems?: LineItem[] }
): number {
  if (!transactionHasManualLineItems(tx)) return 0;
  if (participant.amount <= 0) return 0;

  const exclusive = filterManualLineItems(participant.lineItems).reduce(
    (sum, item) => sum + item.amount,
    0
  );
  const base = participantBaseAmountBeforeFee(tx, participant);
  return Math.max(0, base - exclusive);
}

/** 該員分到的服務費（總應付 − 含費前基礎） */
export function participantServiceFeeShare(
  tx: Transaction,
  participant: { memberId: string; amount: number }
): number {
  if ((tx.serviceFee ?? 0) <= 0 || participant.amount <= 0) return 0;
  const base = participantBaseAmountBeforeFee(tx, participant);
  return Math.max(0, participant.amount - base);
}

/** 合併專屬細項、平分共同消費、服務費、自動找錢明細 */
export function participantLineItemsWithChange(
  tx: Transaction,
  participant: { memberId: string; amount: number; lineItems?: LineItem[] }
): LineItem[] {
  const stored = filterManualLineItems(participant.lineItems);
  const shared = participantSharedConsumptionShare(tx, participant);
  const sharedItems: LineItem[] =
    shared > 0 ? [{ note: SHARED_CONSUMPTION_NOTE, amount: shared }] : [];
  const feeShare = participantServiceFeeShare(tx, participant);
  const feeItems: LineItem[] =
    feeShare > 0 ? [{ note: SERVICE_FEE_NOTE, amount: feeShare }] : [];
  const auto = payerChangeBreakdown(tx, participant.memberId)?.lineItems ?? [];
  return [...stored, ...sharedItems, ...feeItems, ...auto];
}

/** 儲存前為代墊者附加找錢明細 */
export function attachPayerChangeLineItems(transaction: Transaction): void {
  for (const p of transaction.participants) {
    const breakdown = payerChangeBreakdown(transaction, p.memberId);
    if (!breakdown) continue;

    const stored = filterManualLineItems(p.lineItems);
    p.lineItems = [...breakdown.lineItems, ...stored];
  }
}

/** 代墊者顯示：單人「林庭郁」、多人「林庭郁、鄭丞恩」 */
export function formatAdvancePayerNames(
  tx: Transaction,
  nameOf: (id: string) => string
): string {
  const payers = getAdvancePayers(tx);
  if (payers.length === 0) return '—';
  return payers.map((p) => nameOf(p.memberId)).join('、');
}

/** 代墊者＋金額（詳情用） */
export function formatAdvancePayersDetail(
  tx: Transaction,
  nameOf: (id: string) => string
): string {
  const payers = getAdvancePayers(tx);
  if (payers.length === 0) return '—';

  const grossParts = payers.map(
    (p) => `${nameOf(p.memberId)} 實付 NT$ ${p.amount}`
  );
  const change =
    tx.changeAmount ??
    advanceChangeAmount(payers, tx.totalAmount);

  if (change <= 0) {
    if (payers.length === 1) {
      return `${nameOf(payers[0].memberId)}（NT$ ${payers[0].amount}）`;
    }
    return payers
      .map((p) => `${nameOf(p.memberId)} NT$ ${p.amount}`)
      .join('、');
  }

  const netPaid = advanceNetPaidByMember(tx);
  const netParts = payers.map((p) => {
    const net = netPaid.get(p.memberId) ?? p.amount;
    return `${nameOf(p.memberId)} 淨 NT$ ${net}`;
  });

  return `${grossParts.join('、')} · 找零 NT$ ${change} · ${netParts.join('、')}`;
}
