import { LineItem, Transaction } from '../models';
import {
  advanceChangeAmount,
  advanceChangeShareByMember,
  advanceMemberBalances,
  advanceNetPaidByMember,
  advanceSharesByMember,
  getAdvancePayers,
} from '../transactions/advance-allocation';

export interface PayerChangeBreakdown {
  changeShare: number;
  settlementNet: number;
  displayNet: number;
  lineItems: LineItem[];
}

/** 代墊者找錢明細（顯示用，不影響結算） */
export function payerChangeBreakdown(
  tx: Transaction,
  memberId: string
): PayerChangeBreakdown | null {
  const payer = getAdvancePayers(tx).find((p) => p.memberId === memberId);
  if (!payer) return null;

  const changeShare = advanceChangeShareByMember(tx).get(memberId) ?? 0;
  if (changeShare <= 0) return null;

  const share = advanceSharesByMember(tx).get(memberId) ?? 0;
  const settlementNet = advanceMemberBalances(tx).get(memberId) ?? 0;
  const lineItems: LineItem[] = [
    { note: '找錢（已退回）', amount: changeShare },
  ];

  let displayNet = settlementNet;
  if (share === 0) {
    displayNet = payer.amount;
    if (settlementNet > 0) {
      lineItems.push({ note: '待他人結算', amount: settlementNet });
    }
  }

  return { changeShare, settlementNet, displayNet, lineItems };
}

export function isAutoGeneratedLineItem(item: LineItem): boolean {
  return item.note.includes('找錢') || item.note === '待他人結算';
}

/** 過濾系統自動附加的找錢明細（編輯載入用） */
export function filterManualLineItems(items: LineItem[] | undefined): LineItem[] {
  return (items ?? []).filter((item) => !isAutoGeneratedLineItem(item));
}

/** 合併自動找錢明細與手動 line items */
export function participantLineItemsWithChange(
  tx: Transaction,
  participant: { memberId: string; lineItems?: LineItem[] }
): LineItem[] {
  const auto = payerChangeBreakdown(tx, participant.memberId)?.lineItems ?? [];
  const stored = (participant.lineItems ?? []).filter(
    (i) => !i.note.includes('找錢') && i.note !== '待他人結算'
  );
  return [...auto, ...stored];
}

/** 儲存前為代墊者附加找錢明細 */
export function attachPayerChangeLineItems(transaction: Transaction): void {
  for (const p of transaction.participants) {
    const breakdown = payerChangeBreakdown(transaction, p.memberId);
    if (!breakdown) continue;

    const stored = (p.lineItems ?? []).filter(
      (i) => !i.note.includes('找錢') && i.note !== '待他人結算'
    );
    p.lineItems = [...breakdown.lineItems, ...stored];
  }
}

/** 代墊者顯示：單人「林庭郁」、多人「林庭郁、鄭丞恩」 */
export function formatAdvancePayerNames(
  tx: Transaction,
  nameOf: (id: string) => string
): string {
  const payers = getAdvancePayers(tx);
  if (payers.length === 0) return '—';
  return payers.map((p) => nameOf(p.memberId)).join('、');
}

/** 代墊者＋金額（詳情用） */
export function formatAdvancePayersDetail(
  tx: Transaction,
  nameOf: (id: string) => string
): string {
  const payers = getAdvancePayers(tx);
  if (payers.length === 0) return '—';

  const grossParts = payers.map(
    (p) => `${nameOf(p.memberId)} 實付 NT$ ${p.amount}`
  );
  const change =
    tx.changeAmount ??
    advanceChangeAmount(payers, tx.totalAmount);

  if (change <= 0) {
    if (payers.length === 1) {
      return `${nameOf(payers[0].memberId)}（NT$ ${payers[0].amount}）`;
    }
    return payers
      .map((p) => `${nameOf(p.memberId)} NT$ ${p.amount}`)
      .join('、');
  }

  const netPaid = advanceNetPaidByMember(tx);
  const netParts = payers.map((p) => {
    const net = netPaid.get(p.memberId) ?? p.amount;
    return `${nameOf(p.memberId)} 淨 NT$ ${net}`;
  });

  return `${grossParts.join('、')} · 找零 NT$ ${change} · ${netParts.join('、')}`;
}
