import {
  filterManualLineItems,
  isAutoGeneratedLineItem,
} from './advance-display';

describe('advance-display line items', () => {
  it('identifies auto-generated change line items', () => {
    expect(isAutoGeneratedLineItem({ note: '找錢（已退回）', amount: 257 })).toBe(
      true
    );
    expect(isAutoGeneratedLineItem({ note: '待他人結算', amount: 743 })).toBe(
      true
    );
    expect(isAutoGeneratedLineItem({ note: '慕斯瓶', amount: 79 })).toBe(false);
  });

  it('filters manual items for edit hydration', () => {
    expect(
      filterManualLineItems([
        { note: '找錢（已退回）', amount: 257 },
        { note: '慕斯瓶', amount: 79 },
        { note: '待他人結算', amount: 743 },
      ])
    ).toEqual([{ note: '慕斯瓶', amount: 79 }]);
  });
});
